<?php

return [
    'projects' => [
        [
            'id' => 1,
            'title' => 'Portfolio Website',
            'slug' => 'portfolio-website',
            'short_description' => 'A modern personal portfolio built with React and Laravel.',
            'description' => 'This project showcases my work, skills, and experience with a clean and responsive design.',
            'thumbnail' => 'https://via.placeholder.com/600x400?text=Portfolio+Website',
            'github_url' => 'https://github.com/yourusername/portfolio-website',
            'live_url' => 'https://yourwebsite.com',
            'technologies' => ['React', 'Laravel', 'Bootstrap'],
            'is_featured' => true,
            'status' => true,
        ],
        [
            'id' => 2,
            'title' => 'E-Commerce App',
            'slug' => 'e-commerce-app',
            'short_description' => 'An e-commerce application with cart, checkout, and admin features.',
            'description' => 'A complete shopping application with product listings, order flow, and backend APIs.',
            'thumbnail' => 'https://via.placeholder.com/600x400?text=E-Commerce+App',
            'github_url' => 'https://github.com/yourusername/ecommerce-app',
            'live_url' => 'https://shopdemo.com',
            'technologies' => ['React', 'Laravel API', 'MySQL'],
            'is_featured' => true,
            'status' => true,
        ],
        [
            'id' => 3,
            'title' => 'Chat Application',
            'slug' => 'chat-application',
            'short_description' => 'A real-time chat application with modern UI.',
            'description' => 'A live chat app using modern frontend and backend integration.',
            'thumbnail' => 'https://via.placeholder.com/600x400?text=Chat+Application',
            'github_url' => 'https://github.com/yourusername/chat-app',
            'live_url' => 'https://chatdemo.com',
            'technologies' => ['React', 'Node.js', 'Socket.io'],
            'is_featured' => false,
            'status' => true,
        ],

         [
            'id' => 4,
            'title' => 'WEB Application',
            'slug' => 'web-application',
            'short_description' => 'A modern web application with a focus on user experience.',
            'description' => 'A feature-rich web application built with the latest technologies.',
            'thumbnail' => 'https://via.placeholder.com/600x400?text=WEB+Application',
            'github_url' => 'https://github.com/yourusername/web-app',
            'live_url' => 'https://webdemo.com',
            'technologies' => ['React', 'Node.js', 'Socket.io'],
            'is_featured' => false,
            'status' => true,
        ],
    ],
];